 name: Autograding                                                                             
                                                                                                
  on:                                                                                           
    push:                                 
      branches: [ "**" ]                                                                        
                                                                                                
  permissions:                                                                                  
    checks: write                                                                               
    actions: read                                                                               
    contents: read                        

  jobs:                                                                                         
    autograding:
      name: Autograding                                                                         
      runs-on: ubuntu-latest                                                                  

      steps:
        - name: Checkout del repositorio
          uses: actions/checkout@v4           
                                          
        - name: Resultado autograding
          if: always()                                                                          
          uses: education/autograding@v1
          continue-on-error: true                                                               